services:
  db:
    image: postgres:16
    container_name: polipulse-db
    restart: always
    environment:
      POSTGRES_DB: polipulse
      POSTGRES_USER: polipulse_admin
      POSTGRES_PASSWORD: polipulse_admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: polipulse-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
