"""Add MPLADS models

Revision ID: 466aa4b42bcb
Revises: c128406e9457
Create Date: 2026-03-06 12:56:06.553093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '466aa4b42bcb'
down_revision: Union[str, Sequence[str], None] = 'c128406e9457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_posts_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_language'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_leader_name'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_party'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_post_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_posted_at'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('uq_app_users_email_lower'), table_name='app_users', postgresql_where='(email IS NOT NULL)')
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.alter_column('election_results', 'votes_secured',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('election_results', 'vote_share_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('election_results', 'turnout',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('election_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_election_results_constituency_name'), 'election_results', ['constituency_name'], unique=False)
    op.create_index(op.f('ix_election_results_id'), 'election_results', ['id'], unique=False)
    op.create_index(op.f('ix_election_results_party'), 'election_results', ['party'], unique=False)
    op.create_index(op.f('ix_election_results_state_name'), 'election_results', ['state_name'], unique=False)
    op.create_index(op.f('ix_election_results_year'), 'election_results', ['year'], unique=False)
    op.drop_index(op.f('uq_poll_votes_poll_voter'), table_name='poll_votes', postgresql_where='(voter_info IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_poll_votes_poll_voter'), 'poll_votes', ['poll_id', 'voter_info'], unique=True, postgresql_where='(voter_info IS NOT NULL)')
    op.drop_index(op.f('ix_election_results_year'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_state_name'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_party'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_id'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_constituency_name'), table_name='election_results')
    op.alter_column('election_results', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('election_results', 'turnout',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('election_results', 'vote_share_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('election_results', 'votes_secured',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.create_index(op.f('uq_app_users_email_lower'), 'app_users', [sa.literal_column('lower(email::text)')], unique=True, postgresql_where='(email IS NOT NULL)')
    op.create_table('social_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('leader_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('party', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('sentiment_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('retweets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('replies', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('social_posts_pkey'))
    )
    op.create_index(op.f('ix_social_posts_posted_at'), 'social_posts', ['posted_at'], unique=False)
    op.create_index(op.f('ix_social_posts_post_id'), 'social_posts', ['post_id'], unique=True)
    op.create_index(op.f('ix_social_posts_platform'), 'social_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_posts_party'), 'social_posts', ['party'], unique=False)
    op.create_index(op.f('ix_social_posts_leader_name'), 'social_posts', ['leader_name'], unique=False)
    op.create_index(op.f('ix_social_posts_language'), 'social_posts', ['language'], unique=False)
    op.create_index(op.f('ix_social_posts_id'), 'social_posts', ['id'], unique=False)
    # ### end Alembic commands ###
