"""Create all tables

Revision ID: c128406e9457
Revises: 
Create Date: 2026-02-13 16:44:12.187998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c128406e9457'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_category'), 'news_articles', ['category'], unique=False)
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=True),
    sa.Column('ideology', sa.String(length=100), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('states_won', sa.Integer(), nullable=True),
    sa.Column('total_mps', sa.Integer(), nullable=True),
    sa.Column('total_mlas', sa.Integer(), nullable=True),
    sa.Column('vote_share_percentage', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False)
    op.create_index(op.f('ix_parties_name'), 'parties', ['name'], unique=True)
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poll_type', sa.Enum('opinion', 'pre_election', 'policy', name='polltype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_created_at'), 'polls', ['created_at'], unique=False)
    op.create_index(op.f('ix_polls_id'), 'polls', ['id'], unique=False)
    op.create_index(op.f('ix_polls_poll_type'), 'polls', ['poll_type'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('candidate_name', sa.String(length=100), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('predicted_win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('predicted_seats', sa.Integer(), nullable=True),
    sa.Column('seat_range_min', sa.Integer(), nullable=True),
    sa.Column('seat_range_max', sa.Integer(), nullable=True),
    sa.Column('state_name', sa.String(length=120), nullable=True),
    sa.Column('constituency_name', sa.String(length=150), nullable=True),
    sa.Column('predicted_winner', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_candidate_name'), 'predictions', ['candidate_name'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_party'), 'predictions', ['party'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_date'), 'predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_type'), 'predictions', ['prediction_type'], unique=False)
    op.create_table('sentiment_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_data_date'), 'sentiment_data', ['date'], unique=False)
    op.create_index(op.f('ix_sentiment_data_entity_name'), 'sentiment_data', ['entity_name'], unique=False)
    op.create_index(op.f('ix_sentiment_data_id'), 'sentiment_data', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_data_language'), 'sentiment_data', ['language'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('leader_name', sa.String(length=100), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_id'), 'social_posts', ['id'], unique=False)
    op.create_index(op.f('ix_social_posts_language'), 'social_posts', ['language'], unique=False)
    op.create_index(op.f('ix_social_posts_leader_name'), 'social_posts', ['leader_name'], unique=False)
    op.create_index(op.f('ix_social_posts_party'), 'social_posts', ['party'], unique=False)
    op.create_index(op.f('ix_social_posts_platform'), 'social_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_posts_post_id'), 'social_posts', ['post_id'], unique=True)
    op.create_index(op.f('ix_social_posts_posted_at'), 'social_posts', ['posted_at'], unique=False)
    op.create_table('party_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_leaders_id'), 'party_leaders', ['id'], unique=False)
    op.create_index(op.f('ix_party_leaders_name'), 'party_leaders', ['name'], unique=False)
    op.create_index(op.f('ix_party_leaders_party_id'), 'party_leaders', ['party_id'], unique=False)
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.String(length=50), nullable=False),
    sa.Column('voter_info', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_votes_id'), 'poll_votes', ['id'], unique=False)
    op.create_index(op.f('ix_poll_votes_poll_id'), 'poll_votes', ['poll_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_election_results_year'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_state_name'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_party'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_id'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_constituency_name'), table_name='election_results')
    op.alter_column('election_results', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('election_results', 'turnout',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('election_results', 'vote_share_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('election_results', 'votes_secured',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_poll_votes_poll_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_id'), table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index(op.f('ix_party_leaders_party_id'), table_name='party_leaders')
    op.drop_index(op.f('ix_party_leaders_name'), table_name='party_leaders')
    op.drop_index(op.f('ix_party_leaders_id'), table_name='party_leaders')
    op.drop_table('party_leaders')
    op.drop_index(op.f('ix_social_posts_posted_at'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_post_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_party'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_leader_name'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_language'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_sentiment_data_language'), table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_id'), table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_entity_name'), table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_date'), table_name='sentiment_data')
    op.drop_table('sentiment_data')
    op.drop_index(op.f('ix_predictions_prediction_type'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_date'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_party'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_candidate_name'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_polls_poll_type'), table_name='polls')
    op.drop_index(op.f('ix_polls_id'), table_name='polls')
    op.drop_index(op.f('ix_polls_created_at'), table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_parties_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_category'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
